//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Utilities.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculos.
        /// </summary>
        public static string CirclePl {
            get {
                return ResourceManager.GetString("CirclePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista vacía de formas.
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Formas.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimetro.
        /// </summary>
        public static string Perimeter {
            get {
                return ResourceManager.GetString("Perimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangulo.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangles.
        /// </summary>
        public static string RectanglePl {
            get {
                return ResourceManager.GetString("RectanglePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formas.
        /// </summary>
        public static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrados.
        /// </summary>
        public static string SquarePl {
            get {
                return ResourceManager.GetString("SquarePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo.
        /// </summary>
        public static string Triangle {
            get {
                return ResourceManager.GetString("Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulos.
        /// </summary>
        public static string TrianglePl {
            get {
                return ResourceManager.GetString("TrianglePl", resourceCulture);
            }
        }
    }
}
